import importlib.util
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "hc_signal_watch_report.py"


def _module():
    spec = importlib.util.spec_from_file_location("hc_signal_watch_report", SCRIPT)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules["hc_signal_watch_report"] = module
    spec.loader.exec_module(module)
    return module


def _ingest_module():
    ingest_script = ROOT / "scripts" / "hc_signal_watch_rss_ingest.py"
    spec = importlib.util.spec_from_file_location("hc_signal_watch_rss_ingest_for_report", ingest_script)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules["hc_signal_watch_rss_ingest_for_report"] = module
    spec.loader.exec_module(module)
    return module


def test_signal_watch_report_is_report_only() -> None:
    module = _module()

    report = module.build_report(ROOT)

    assert report["advisory_only"] is True
    assert report["public_safe"] is True
    assert report["truth_guarantee"] is False
    assert report["human_review_required"] is True
    assert report["network_access"] is False
    assert report["repository_mutation"] is False
    assert report["approval_authority"] is False
    assert report["merge_authority"] is False

def test_signal_watch_report_contains_recommended_human_actions(tmp_path: Path) -> None:
    module = _module()
    signal_file = tmp_path / "signals.json"
    signal_file.write_text(
        json.dumps([{"source": "GitHub Home", "title": "First external star on the repository"}]),
        encoding="utf-8",
    )

    report = module.build_report(ROOT, signal_file)

    assert "recommended_human_actions" in report
    assert report["recommended_human_actions"] == [
        {
            "priority": "P3",
            "source": "GitHub Home",
            "reason": "operator signal classified as low risk with community impact",
            "recommended_action": "inspect onboarding and public safety language",
            "human_review_required": True,
            "automation_boundary": module.ACTION_AUTOMATION_BOUNDARY,
        }
    ]


def test_signal_watch_recommended_human_actions_prioritize_fixture_risks(tmp_path: Path) -> None:
    module = _module()
    payload = {
        "mode": "local_fixture_only",
        "network_access": False,
        "signals": [
            {
                "source": "GitHub Changelog fixture",
                "title": "GitHub Actions runner update",
                "risk": "medium",
                "recommended_action": "inspect workflow action versions and warnings",
                "classification_reason": "workflow runtime signal",
                "evidence_gap": "missing local workflow context",
            },
            {
                "source": "GitHub Changelog fixture",
                "title": "Secret scanning update",
                "risk": "high",
                "recommended_action": "inspect advisory security signal interpretation",
                "classification_reason": "code scanning, secret scanning, or supply-chain signal",
                "evidence_gap": "missing local alert context",
            },
        ],
    }
    payload_path = tmp_path / "changelog-signals.json"
    payload_path.write_text(json.dumps(payload), encoding="utf-8")

    report = module.build_report(ROOT, changelog_signals_file=payload_path)

    actions = report["recommended_human_actions"]
    assert [action["priority"] for action in actions] == ["P1", "P2"]
    assert actions[0]["recommended_action"] == "inspect advisory security signal interpretation"
    assert actions[0]["reason"] == "missing local alert context"
    assert actions[1]["recommended_action"] == "inspect workflow action versions and warnings"
    assert actions[1]["reason"] == "missing local workflow context"
    assert report["network_access"] is False
    assert report["repository_mutation"] is False
    assert report["approval_authority"] is False
    assert report["merge_authority"] is False
    assert all("no live network" in action["automation_boundary"] for action in actions)
    assert all("no GitHub API calls" in action["automation_boundary"] for action in actions)
    assert all("no approval authority" in action["automation_boundary"] for action in actions)
    assert all("no merge authority" in action["automation_boundary"] for action in actions)


def test_signal_watch_recommended_human_actions_empty_markdown_message() -> None:
    module = _module()

    markdown = module.render_markdown(module.build_report(ROOT))

    assert "## Recommended human actions" in markdown
    assert "No recommended human actions were generated by this local report." in markdown


def test_signal_watch_report_confirms_local_policy_links() -> None:
    module = _module()

    report = module.build_report(ROOT)

    assert report["policy"]["present"] is True
    assert report["policy"]["requires_repo_wide_pr_search"] is True
    assert report["policy"]["requires_annotation_review"] is True
    assert report["policy"]["requires_community_signal_review"] is True
    assert report["active_work_registry"]["links_policy"] is True


def test_signal_watch_report_confirms_dependabot_config() -> None:
    module = _module()

    report = module.build_report(ROOT)

    assert report["dependabot"]["present"] is True
    assert report["dependabot"]["github_actions_weekly"] is True
    assert report["dependabot"]["pip_weekly"] is True
    assert report["dependabot"]["github_actions_grouped"] is True


def test_signal_watch_classifies_operator_supplied_signals(tmp_path: Path) -> None:
    module = _module()
    signal_file = tmp_path / "signals.json"
    signal_file.write_text(
        json.dumps(
            [
                {
                    "source": "GitHub Changelog",
                    "title": "Actions runtime deprecation notice for Node",
                    "url": "https://example.invalid/actions-node",
                },
                {
                    "source": "GitHub Home",
                    "title": "First external star on the repository",
                },
                {
                    "source": "GitHub Changelog",
                    "title": "Unrelated UI theme update",
                },
            ]
        ),
        encoding="utf-8",
    )

    report = module.build_report(ROOT, signal_file)

    assert [finding["impact"] for finding in report["signals"]] == ["workflow", "community", "none"]
    assert report["signals"][0]["recommended_action"] == "inspect workflow action versions and warnings"
    assert report["signals"][1]["recommended_action"] == "inspect onboarding and public safety language"
    assert report["signals"][2]["evidence_gap"] == "no HC-relevant keyword matched this signal"


def test_signal_watch_markdown_keeps_safety_markers() -> None:
    module = _module()

    markdown = module.render_markdown(module.build_report(ROOT))

    assert "advisory_only=true" in markdown
    assert "public_safe=true" in markdown
    assert "truth_guarantee=false" in markdown
    assert "human_review_required=true" in markdown
    assert "repository_mutation=false" in markdown
    assert "issue_comment_automation=false" in markdown
    assert "label_reviewer_mutation=false" in markdown
    assert "merge_authority=false" in markdown


def test_signal_watch_imports_changelog_fixture_signals_json(tmp_path: Path) -> None:
    module = _module()
    fixture = ROOT / "examples" / "hc-signal-watch" / "github-changelog-signals-fixture.json"
    ingest_script = ROOT / "scripts" / "hc_signal_watch_rss_ingest.py"
    spec = importlib.util.spec_from_file_location("hc_signal_watch_rss_ingest_for_report", ingest_script)
    assert spec is not None
    assert spec.loader is not None
    ingest = importlib.util.module_from_spec(spec)
    sys.modules["hc_signal_watch_rss_ingest_for_report"] = ingest
    spec.loader.exec_module(ingest)

    payload_path = tmp_path / "github-changelog-normalized.json"
    payload_path.write_text(
        json.dumps(ingest.normalize_entries(ingest.load_fixture(fixture))),
        encoding="utf-8",
    )

    report = module.build_report(ROOT, changelog_signals_file=payload_path)

    signals = report["github_changelog_fixture_signals"]
    assert len(signals) == 2
    assert signals[0]["source"] == "GitHub Changelog fixture"
    assert signals[0]["title"] == "Secret scanning update"
    assert signals[0]["url"] == "https://example.invalid/github-changelog/secret-scanning"
    assert signals[0]["published"] == "2026-06-16T12:00:00Z"
    assert signals[0]["category"] == "security"
    assert signals[0]["impact"] == "security"
    assert signals[0]["risk"] == "high"
    assert signals[0]["recommended_action"] == "inspect advisory security signal interpretation"
    assert signals[0]["classification_reason"] == "code scanning, secret scanning, or supply-chain signal"
    assert signals[0]["matched_keywords"] == ["secret scanning"]
    assert signals[0]["evidence_gap"] is None
    assert signals[0]["automation_boundary"] == "advisory-only; no issue/comment automation, labels, reviewers, approval, or merge"
    assert signals[0]["dedupe_key"] == "url:https://example.invalid/github-changelog/secret-scanning"


def test_signal_watch_markdown_includes_changelog_fixture_section(tmp_path: Path) -> None:
    module = _module()
    payload = {
        "mode": "local_fixture_only",
        "network_access": False,
        "signals": [
            {
                "source": "GitHub Changelog fixture",
                "title": "GitHub Actions runner update",
                "impact": "workflow",
                "risk": "medium",
                "recommended_action": "inspect workflow action versions and warnings",
                "matched_keywords": ["actions", "runner"],
                "automation_boundary": "advisory-only; no issue/comment automation, labels, reviewers, approval, or merge",
                "dedupe_key": "url:https://example.invalid/actions-runner",
            }
        ],
    }
    payload_path = tmp_path / "changelog-signals.json"
    payload_path.write_text(json.dumps(payload), encoding="utf-8")

    markdown = module.render_markdown(module.build_report(ROOT, changelog_signals_file=payload_path))

    assert "## GitHub Changelog fixture signals" in markdown
    assert "## Recommended human actions" in markdown
    assert "### GitHub Actions runner update" in markdown
    assert "- matched_keywords: actions, runner" in markdown
    assert "- dedupe_key: url:https://example.invalid/actions-runner" in markdown


def test_signal_watch_missing_changelog_input_keeps_current_behavior() -> None:
    module = _module()

    report = module.build_report(ROOT)

    assert report["github_changelog_fixture_signals"] == []
    assert report["signals"] == []
    assert "No signal JSON was supplied" in report["evidence_gaps"][0]


def test_signal_watch_changelog_signal_file_fails_safely(tmp_path: Path) -> None:
    module = _module()
    malformed = tmp_path / "malformed.json"
    malformed.write_text("not json", encoding="utf-8")

    try:
        module.build_report(ROOT, changelog_signals_file=malformed)
    except ValueError as exc:
        assert "changelog signal file is not valid JSON" in str(exc)
    else:
        raise AssertionError("malformed changelog signal file should fail safely")

    missing = tmp_path / "missing.json"
    try:
        module.build_report(ROOT, changelog_signals_file=missing)
    except ValueError as exc:
        assert "changelog signal file not found" in str(exc)
    else:
        raise AssertionError("missing changelog signal file should fail safely")


def test_signal_watch_local_rss_fixture_report_golden_snapshot(tmp_path: Path) -> None:
    report_module = _module()
    ingest = _ingest_module()
    fixture = ROOT / "examples" / "hc-signal-watch" / "github-changelog-rss-fixture.xml"

    normalized_path = tmp_path / "github-changelog-rss-normalized.json"
    normalized_path.write_text(
        json.dumps(ingest.normalize_entries(ingest.load_fixture(fixture))),
        encoding="utf-8",
    )

    report = report_module.build_report(ROOT, changelog_signals_file=normalized_path)
    markdown = report_module.render_markdown(report)

    assert report["advisory_only"] is True
    assert report["public_safe"] is True
    assert report["truth_guarantee"] is False
    assert report["human_review_required"] is True
    assert report["mode"] == "local_report_only"
    assert report["network_access"] is False
    assert report["repository_mutation"] is False
    assert report["issue_comment_automation"] is False
    assert report["label_reviewer_mutation"] is False
    assert report["approval_authority"] is False
    assert report["merge_authority"] is False
    assert "github_changelog_fixture_signals" in report
    assert "recommended_human_actions" in report

    signals = report["github_changelog_fixture_signals"]
    assert signals
    assert any(signal["risk"] == "medium" for signal in signals)
    expected_fields = {
        "title",
        "category",
        "impact",
        "risk",
        "recommended_action",
        "classification_reason",
        "matched_keywords",
        "automation_boundary",
        "dedupe_key",
    }
    assert expected_fields <= signals[0].keys()

    assert "# HC GitHub Signal Watch" in markdown
    assert "## Safety markers" in markdown
    assert "## GitHub Changelog fixture signals" in markdown
    assert "network_access=false" in markdown
    assert "repository_mutation=false" in markdown
    assert "approval_authority=false" in markdown
    assert "merge_authority=false" in markdown
    assert signals[0]["title"] in markdown


def test_signal_watch_report_accepts_live_rss_dry_run_changelog_input(tmp_path: Path) -> None:
    module = _module()
    payload = {
        "mode": "manual_live_rss_dry_run",
        "network_access": True,
        "safe_failure": False,
        "fetch_status": "ok",
        "signals": [
            {
                "source": "GitHub Changelog RSS live dry run",
                "title": "Secret scanning update",
                "risk": "high",
                "recommended_action": "inspect advisory security signal interpretation",
                "classification_reason": "code scanning, secret scanning, or supply-chain signal",
                "evidence_gap": None,
            }
        ],
    }
    payload_path = tmp_path / "live-rss-signals.json"
    payload_path.write_text(json.dumps(payload), encoding="utf-8")

    report = module.build_report(ROOT, changelog_signals_file=payload_path)

    assert report["github_changelog_fixture_signals"][0]["title"] == "Secret scanning update"
    assert report["recommended_human_actions"][0]["priority"] == "P1"
    assert report["recommended_human_actions"][0]["recommended_action"] == "inspect advisory security signal interpretation"


def test_signal_watch_report_live_rss_safe_failure_stays_quiet(tmp_path: Path) -> None:
    module = _module()
    payload = {
        "mode": "manual_live_rss_dry_run",
        "network_access": True,
        "safe_failure": True,
        "fetch_status": "error",
        "fetch_error": "timeout while fetching RSS",
        "signals": [
            {
                "source": "GitHub Changelog RSS live dry run",
                "title": "Secret scanning update",
                "risk": "high",
                "recommended_action": "inspect advisory security signal interpretation",
            }
        ],
    }
    payload_path = tmp_path / "live-rss-safe-failure.json"
    payload_path.write_text(json.dumps(payload), encoding="utf-8")

    report = module.build_report(ROOT, changelog_signals_file=payload_path)

    assert report["github_changelog_fixture_signals"] == []
    assert report["recommended_human_actions"] == []
